//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RusoCars.Models
{
    public partial class News
    {
        public int NewsId { get; set; }
        public string Title { get; set; }
        public int ImageId { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Image Image { get; set; }
    }
    
}
