//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RusoCars.Models
{
    public partial class Service
    {
        public int ServiceId { get; set; }
        public string Name { get; set; }
        public bool isCompetition { get; set; }
        public int BeforeImage { get; set; }
        public int AfterImage { get; set; }
        public string Description { get; set; }
    
        public virtual Image ImageAfter { get; set; }
        public virtual Image ImageBefore { get; set; }
    }
    
}
