//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RusoCars.Models
{
    public partial class Subcategory
    {
        public Subcategory()
        {
            this.Subcategories_Images = new HashSet<Subcategories_Images>();
        }
    
        public int SubcategoryId { get; set; }
        public string Name { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Subcategories_Images> Subcategories_Images { get; set; }
    }
    
}
