//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RusoCars.Models
{
    public partial class Subcategories_Images
    {
        public int ImageId { get; set; }
        public int SubcategoryId { get; set; }
        public int Subcategory_ImageId { get; set; }
    
        public virtual Image Image { get; set; }
        public virtual Subcategory Subcategory { get; set; }
    }
    
}
