//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RusoCars.Models
{
    public partial class Text
    {
        public int TextId { get; set; }
        public int LanguageId { get; set; }
        public string Descriptor { get; set; }
        public string Content { get; set; }
    
        public virtual Language Language { get; set; }
    }
    
}
