//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace RusoCars.Models
{
    public partial class Category
    {
        public Category()
        {
            this.Subcategories = new HashSet<Subcategory>();
        }
    
        public int CategoryId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Subcategory> Subcategories { get; set; }
    }
    
}
